-- Migration initiale V1 : création de toutes les tables

CREATE TABLE IF NOT EXISTS deceased (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossierNumber VARCHAR(20) NOT NULL UNIQUE,
    lastName VARCHAR(100) NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    birthDate DATE,
    deathDate DATE,
    placeOfDeath VARCHAR(255),
    causeOfDeath VARCHAR(255),
    gender VARCHAR(255),
    nir VARCHAR(20),
    observations TEXT,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_deceased_dossier ON deceased(dossierNumber);
CREATE INDEX IF NOT EXISTS idx_deceased_lastName ON deceased(lastName);
CREATE INDEX IF NOT EXISTS idx_deceased_fullName ON deceased(lastName, firstName);
CREATE INDEX IF NOT EXISTS idx_deceased_deathDate ON deceased(deathDate);
CREATE INDEX IF NOT EXISTS idx_deceased_createdAt ON deceased(createdAt);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    fullName VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL,
    email VARCHAR(150) UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    lastLogin TIMESTAMP,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

CREATE TABLE IF NOT EXISTS storage_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    label VARCHAR(100) NOT NULL,
    zone VARCHAR(20) NOT NULL,
    capacity INT DEFAULT 0,
    temperature INT DEFAULT 0,
    occupied BOOLEAN DEFAULT FALSE,
    notes TEXT,
    createdAt TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_storage_code ON storage_locations(code);
CREATE INDEX IF NOT EXISTS idx_storage_zone ON storage_locations(zone);
CREATE INDEX IF NOT EXISTS idx_storage_occupied ON storage_locations(occupied);

CREATE TABLE IF NOT EXISTS storage_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deceased_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    assignedAt TIMESTAMP NOT NULL,
    releasedAt TIMESTAMP,
    releasedBy VARCHAR(50),
    FOREIGN KEY (deceased_id) REFERENCES deceased(id),
    FOREIGN KEY (location_id) REFERENCES storage_locations(id)
);

CREATE INDEX IF NOT EXISTS idx_assign_deceased ON storage_assignments(deceased_id);
CREATE INDEX IF NOT EXISTS idx_assign_location ON storage_assignments(location_id);
CREATE INDEX IF NOT EXISTS idx_assign_active ON storage_assignments(releasedAt);

CREATE TABLE IF NOT EXISTS interventions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deceased_id BIGINT NOT NULL,
    performer_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    scheduledAt TIMESTAMP NOT NULL,
    completedAt TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    report TEXT,
    productsUsed TEXT,
    signedBy VARCHAR(255),
    signedAt TIMESTAMP,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP,
    FOREIGN KEY (deceased_id) REFERENCES deceased(id),
    FOREIGN KEY (performer_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_interventions_status ON interventions(status);
CREATE INDEX IF NOT EXISTS idx_interventions_scheduled ON interventions(scheduledAt);
CREATE INDEX IF NOT EXISTS idx_interventions_deceased ON interventions(deceased_id);

CREATE TABLE IF NOT EXISTS exit_authorizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deceased_id BIGINT NOT NULL,
    authorized_by BIGINT NOT NULL,
    authorizedAt TIMESTAMP NOT NULL,
    transportCompany VARCHAR(150) NOT NULL,
    authorizedPerson VARCHAR(100),
    notes TEXT,
    status VARCHAR(20) NOT NULL,
    effectiveExitAt TIMESTAMP,
    signedBy VARCHAR(255),
    signedAt TIMESTAMP,
    certificateOfDeathVerified BOOLEAN DEFAULT FALSE,
    authorizationFormVerified BOOLEAN DEFAULT FALSE,
    identityVerified BOOLEAN DEFAULT FALSE,
    verificationNotes TEXT,
    FOREIGN KEY (deceased_id) REFERENCES deceased(id),
    FOREIGN KEY (authorized_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_exit_status ON exit_authorizations(status);
CREATE INDEX IF NOT EXISTS idx_exit_deceased ON exit_authorizations(deceased_id);
CREATE INDEX IF NOT EXISTS idx_exit_authorized ON exit_authorizations(authorizedAt);

CREATE TABLE IF NOT EXISTS family_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deceased_id BIGINT,
    fullName VARCHAR(255),
    relationship VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255),
    notes TEXT,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP,
    FOREIGN KEY (deceased_id) REFERENCES deceased(id)
);

CREATE TABLE IF NOT EXISTS attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entityType VARCHAR(255) NOT NULL,
    entityId BIGINT NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    mimeType VARCHAR(255),
    fileSize BIGINT,
    uploadedAt TIMESTAMP,
    description VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_attachments_entity ON attachments(entityType, entityId);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(50) NOT NULL,
    entityType VARCHAR(100),
    entityId BIGINT,
    details TEXT,
    timestamp TIMESTAMP NOT NULL,
    ipAddress VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);
